// <auto-generated />
using GestionClientesEcoMercadoAustral.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GestionClientesEcoMercadoAustral.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("GestionClientesEcoMercadoAustral.Models.Cliente", b =>
                {
                    b.Property<int>("ClienteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ClienteId"));

                    b.Property<string>("Apellido1")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Apellido2")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ComunaId")
                        .HasColumnType("int");

                    b.Property<string>("Direccion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Rut")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("SegmentoClienteId")
                        .HasColumnType("int");

                    b.Property<string>("TipoCliente")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.HasKey("ClienteId");

                    b.HasIndex("ComunaId");

                    b.HasIndex("Rut")
                        .IsUnique();

                    b.HasIndex("SegmentoClienteId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Clientes");
                });

            modelBuilder.Entity("GestionClientesEcoMercadoAustral.Models.Comuna", b =>
                {
                    b.Property<int>("ComunaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ComunaId"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RegionId")
                        .HasColumnType("int");

                    b.HasKey("ComunaId");

                    b.HasIndex("RegionId");

                    b.ToTable("Comunas");

                    b.HasData(
                        new
                        {
                            ComunaId = 1,
                            Nombre = "Arica",
                            RegionId = 1
                        },
                        new
                        {
                            ComunaId = 2,
                            Nombre = "Camarones",
                            RegionId = 1
                        },
                        new
                        {
                            ComunaId = 3,
                            Nombre = "Putre",
                            RegionId = 1
                        },
                        new
                        {
                            ComunaId = 4,
                            Nombre = "General Lagos",
                            RegionId = 1
                        },
                        new
                        {
                            ComunaId = 6,
                            Nombre = "Alto Hospicio",
                            RegionId = 2
                        },
                        new
                        {
                            ComunaId = 7,
                            Nombre = "Pozo Almonte",
                            RegionId = 2
                        },
                        new
                        {
                            ComunaId = 8,
                            Nombre = "Camiña",
                            RegionId = 2
                        },
                        new
                        {
                            ComunaId = 9,
                            Nombre = "Colchane",
                            RegionId = 2
                        },
                        new
                        {
                            ComunaId = 10,
                            Nombre = "Huara",
                            RegionId = 2
                        },
                        new
                        {
                            ComunaId = 11,
                            Nombre = "Pica",
                            RegionId = 2
                        },
                        new
                        {
                            ComunaId = 5,
                            Nombre = "Iquique",
                            RegionId = 2
                        },
                        new
                        {
                            ComunaId = 12,
                            Nombre = "Antofagasta",
                            RegionId = 3
                        },
                        new
                        {
                            ComunaId = 13,
                            Nombre = "Mejillones",
                            RegionId = 3
                        },
                        new
                        {
                            ComunaId = 14,
                            Nombre = "Sierra Gorda",
                            RegionId = 3
                        },
                        new
                        {
                            ComunaId = 15,
                            Nombre = "Taltal",
                            RegionId = 3
                        },
                        new
                        {
                            ComunaId = 16,
                            Nombre = "Calama",
                            RegionId = 3
                        },
                        new
                        {
                            ComunaId = 17,
                            Nombre = "San Pedro de Atacama",
                            RegionId = 3
                        },
                        new
                        {
                            ComunaId = 18,
                            Nombre = "Ollagüe",
                            RegionId = 3
                        },
                        new
                        {
                            ComunaId = 19,
                            Nombre = "Tocopilla",
                            RegionId = 3
                        },
                        new
                        {
                            ComunaId = 20,
                            Nombre = "María Elena",
                            RegionId = 3
                        },
                        new
                        {
                            ComunaId = 21,
                            Nombre = "Copiapó",
                            RegionId = 4
                        },
                        new
                        {
                            ComunaId = 22,
                            Nombre = "Caldera",
                            RegionId = 4
                        },
                        new
                        {
                            ComunaId = 23,
                            Nombre = "Tierra Amarilla",
                            RegionId = 4
                        },
                        new
                        {
                            ComunaId = 24,
                            Nombre = "Chañaral",
                            RegionId = 4
                        },
                        new
                        {
                            ComunaId = 25,
                            Nombre = "Diego de Almagro",
                            RegionId = 4
                        },
                        new
                        {
                            ComunaId = 26,
                            Nombre = "Vallenar",
                            RegionId = 4
                        },
                        new
                        {
                            ComunaId = 27,
                            Nombre = "Huasco",
                            RegionId = 4
                        },
                        new
                        {
                            ComunaId = 28,
                            Nombre = "Freirina",
                            RegionId = 4
                        },
                        new
                        {
                            ComunaId = 29,
                            Nombre = "Alto del Carmen",
                            RegionId = 4
                        },
                        new
                        {
                            ComunaId = 30,
                            Nombre = "La Serena",
                            RegionId = 5
                        },
                        new
                        {
                            ComunaId = 31,
                            Nombre = "Coquimbo",
                            RegionId = 5
                        },
                        new
                        {
                            ComunaId = 32,
                            Nombre = "Andacollo",
                            RegionId = 5
                        },
                        new
                        {
                            ComunaId = 33,
                            Nombre = "La Higuera",
                            RegionId = 5
                        },
                        new
                        {
                            ComunaId = 34,
                            Nombre = "Paihuano",
                            RegionId = 5
                        },
                        new
                        {
                            ComunaId = 35,
                            Nombre = "Vicuña",
                            RegionId = 5
                        },
                        new
                        {
                            ComunaId = 36,
                            Nombre = "Illapel",
                            RegionId = 5
                        },
                        new
                        {
                            ComunaId = 37,
                            Nombre = "Los Vilos",
                            RegionId = 5
                        },
                        new
                        {
                            ComunaId = 38,
                            Nombre = "Salamanca",
                            RegionId = 5
                        },
                        new
                        {
                            ComunaId = 39,
                            Nombre = "Ovalle",
                            RegionId = 5
                        },
                        new
                        {
                            ComunaId = 40,
                            Nombre = "Combarbalá",
                            RegionId = 5
                        },
                        new
                        {
                            ComunaId = 41,
                            Nombre = "Monte Patria",
                            RegionId = 5
                        },
                        new
                        {
                            ComunaId = 42,
                            Nombre = "Punitaqui",
                            RegionId = 5
                        },
                        new
                        {
                            ComunaId = 43,
                            Nombre = "Río Hurtado",
                            RegionId = 5
                        },
                        new
                        {
                            ComunaId = 44,
                            Nombre = "Valparaíso",
                            RegionId = 6
                        },
                        new
                        {
                            ComunaId = 45,
                            Nombre = "Viña del Mar",
                            RegionId = 6
                        },
                        new
                        {
                            ComunaId = 46,
                            Nombre = "Concón",
                            RegionId = 6
                        },
                        new
                        {
                            ComunaId = 47,
                            Nombre = "Quintero",
                            RegionId = 6
                        },
                        new
                        {
                            ComunaId = 48,
                            Nombre = "Puchuncaví",
                            RegionId = 6
                        },
                        new
                        {
                            ComunaId = 49,
                            Nombre = "Casablanca",
                            RegionId = 6
                        },
                        new
                        {
                            ComunaId = 50,
                            Nombre = "Juan Fernández",
                            RegionId = 6
                        },
                        new
                        {
                            ComunaId = 51,
                            Nombre = "Quilpué",
                            RegionId = 6
                        },
                        new
                        {
                            ComunaId = 52,
                            Nombre = "Villa Alemana",
                            RegionId = 6
                        },
                        new
                        {
                            ComunaId = 53,
                            Nombre = "Limache",
                            RegionId = 6
                        },
                        new
                        {
                            ComunaId = 54,
                            Nombre = "Olmué",
                            RegionId = 6
                        },
                        new
                        {
                            ComunaId = 55,
                            Nombre = "Quillota",
                            RegionId = 6
                        },
                        new
                        {
                            ComunaId = 56,
                            Nombre = "La Calera",
                            RegionId = 6
                        },
                        new
                        {
                            ComunaId = 57,
                            Nombre = "La Cruz",
                            RegionId = 6
                        },
                        new
                        {
                            ComunaId = 58,
                            Nombre = "Nogales",
                            RegionId = 6
                        },
                        new
                        {
                            ComunaId = 59,
                            Nombre = "Hijuelas",
                            RegionId = 6
                        },
                        new
                        {
                            ComunaId = 60,
                            Nombre = "San Antonio",
                            RegionId = 6
                        },
                        new
                        {
                            ComunaId = 61,
                            Nombre = "Cartagena",
                            RegionId = 6
                        },
                        new
                        {
                            ComunaId = 62,
                            Nombre = "El Tabo",
                            RegionId = 6
                        },
                        new
                        {
                            ComunaId = 63,
                            Nombre = "El Quisco",
                            RegionId = 6
                        },
                        new
                        {
                            ComunaId = 64,
                            Nombre = "Algarrobo",
                            RegionId = 6
                        },
                        new
                        {
                            ComunaId = 65,
                            Nombre = "Santo Domingo",
                            RegionId = 6
                        },
                        new
                        {
                            ComunaId = 66,
                            Nombre = "San Felipe",
                            RegionId = 6
                        },
                        new
                        {
                            ComunaId = 67,
                            Nombre = "Llaillay",
                            RegionId = 6
                        },
                        new
                        {
                            ComunaId = 68,
                            Nombre = "Catemu",
                            RegionId = 6
                        },
                        new
                        {
                            ComunaId = 69,
                            Nombre = "Putaendo",
                            RegionId = 6
                        },
                        new
                        {
                            ComunaId = 70,
                            Nombre = "Santa María",
                            RegionId = 6
                        },
                        new
                        {
                            ComunaId = 71,
                            Nombre = "Panquehue",
                            RegionId = 6
                        },
                        new
                        {
                            ComunaId = 72,
                            Nombre = "Santiago",
                            RegionId = 7
                        },
                        new
                        {
                            ComunaId = 73,
                            Nombre = "Cerrillos",
                            RegionId = 7
                        },
                        new
                        {
                            ComunaId = 74,
                            Nombre = "Cerro Navia",
                            RegionId = 7
                        },
                        new
                        {
                            ComunaId = 75,
                            Nombre = "Conchalí",
                            RegionId = 7
                        },
                        new
                        {
                            ComunaId = 76,
                            Nombre = "El Bosque",
                            RegionId = 7
                        },
                        new
                        {
                            ComunaId = 77,
                            Nombre = "Estación Central",
                            RegionId = 7
                        },
                        new
                        {
                            ComunaId = 78,
                            Nombre = "Huechuraba",
                            RegionId = 7
                        },
                        new
                        {
                            ComunaId = 79,
                            Nombre = "Independencia",
                            RegionId = 7
                        },
                        new
                        {
                            ComunaId = 80,
                            Nombre = "La Cisterna",
                            RegionId = 7
                        },
                        new
                        {
                            ComunaId = 81,
                            Nombre = "La Florida",
                            RegionId = 7
                        },
                        new
                        {
                            ComunaId = 82,
                            Nombre = "La Granja",
                            RegionId = 7
                        },
                        new
                        {
                            ComunaId = 83,
                            Nombre = "La Pintana",
                            RegionId = 7
                        },
                        new
                        {
                            ComunaId = 84,
                            Nombre = "La Reina",
                            RegionId = 7
                        },
                        new
                        {
                            ComunaId = 85,
                            Nombre = "Las Condes",
                            RegionId = 7
                        },
                        new
                        {
                            ComunaId = 86,
                            Nombre = "Lo Barnechea",
                            RegionId = 7
                        },
                        new
                        {
                            ComunaId = 87,
                            Nombre = "Lo Espejo",
                            RegionId = 7
                        },
                        new
                        {
                            ComunaId = 88,
                            Nombre = "Lo Prado",
                            RegionId = 7
                        },
                        new
                        {
                            ComunaId = 89,
                            Nombre = "Macul",
                            RegionId = 7
                        },
                        new
                        {
                            ComunaId = 90,
                            Nombre = "Maipú",
                            RegionId = 7
                        },
                        new
                        {
                            ComunaId = 91,
                            Nombre = "Ñuñoa",
                            RegionId = 7
                        },
                        new
                        {
                            ComunaId = 92,
                            Nombre = "Pedro Aguirre Cerda",
                            RegionId = 7
                        },
                        new
                        {
                            ComunaId = 93,
                            Nombre = "Peñalolén",
                            RegionId = 7
                        },
                        new
                        {
                            ComunaId = 94,
                            Nombre = "Providencia",
                            RegionId = 7
                        },
                        new
                        {
                            ComunaId = 95,
                            Nombre = "Pudahuel",
                            RegionId = 7
                        },
                        new
                        {
                            ComunaId = 96,
                            Nombre = "Quilicura",
                            RegionId = 7
                        },
                        new
                        {
                            ComunaId = 97,
                            Nombre = "Quinta Normal",
                            RegionId = 7
                        },
                        new
                        {
                            ComunaId = 98,
                            Nombre = "Recoleta",
                            RegionId = 7
                        },
                        new
                        {
                            ComunaId = 99,
                            Nombre = "Renca",
                            RegionId = 7
                        },
                        new
                        {
                            ComunaId = 100,
                            Nombre = "San Joaquín",
                            RegionId = 7
                        },
                        new
                        {
                            ComunaId = 101,
                            Nombre = "San Miguel",
                            RegionId = 7
                        },
                        new
                        {
                            ComunaId = 102,
                            Nombre = "San Ramón",
                            RegionId = 7
                        },
                        new
                        {
                            ComunaId = 103,
                            Nombre = "Vitacura",
                            RegionId = 7
                        },
                        new
                        {
                            ComunaId = 104,
                            Nombre = "Puente Alto",
                            RegionId = 7
                        },
                        new
                        {
                            ComunaId = 105,
                            Nombre = "Pirque",
                            RegionId = 7
                        },
                        new
                        {
                            ComunaId = 106,
                            Nombre = "San José de Maipo",
                            RegionId = 7
                        },
                        new
                        {
                            ComunaId = 107,
                            Nombre = "Colina",
                            RegionId = 7
                        },
                        new
                        {
                            ComunaId = 108,
                            Nombre = "Lampa",
                            RegionId = 7
                        },
                        new
                        {
                            ComunaId = 109,
                            Nombre = "Tiltil",
                            RegionId = 7
                        },
                        new
                        {
                            ComunaId = 110,
                            Nombre = "Talagante",
                            RegionId = 7
                        },
                        new
                        {
                            ComunaId = 111,
                            Nombre = "El Monte",
                            RegionId = 7
                        },
                        new
                        {
                            ComunaId = 112,
                            Nombre = "Isla de Maipo",
                            RegionId = 7
                        },
                        new
                        {
                            ComunaId = 113,
                            Nombre = "Padre Hurtado",
                            RegionId = 7
                        },
                        new
                        {
                            ComunaId = 114,
                            Nombre = "Peñaflor",
                            RegionId = 7
                        },
                        new
                        {
                            ComunaId = 115,
                            Nombre = "Melipilla",
                            RegionId = 7
                        },
                        new
                        {
                            ComunaId = 116,
                            Nombre = "Curacaví",
                            RegionId = 7
                        },
                        new
                        {
                            ComunaId = 117,
                            Nombre = "María Pinto",
                            RegionId = 7
                        },
                        new
                        {
                            ComunaId = 118,
                            Nombre = "San Pedro",
                            RegionId = 7
                        },
                        new
                        {
                            ComunaId = 119,
                            Nombre = "Buin",
                            RegionId = 7
                        },
                        new
                        {
                            ComunaId = 120,
                            Nombre = "Calera de Tango",
                            RegionId = 7
                        },
                        new
                        {
                            ComunaId = 121,
                            Nombre = "Paine",
                            RegionId = 7
                        },
                        new
                        {
                            ComunaId = 122,
                            Nombre = "San Bernardo",
                            RegionId = 7
                        },
                        new
                        {
                            ComunaId = 123,
                            Nombre = "Rancagua",
                            RegionId = 8
                        },
                        new
                        {
                            ComunaId = 124,
                            Nombre = "Machalí",
                            RegionId = 8
                        },
                        new
                        {
                            ComunaId = 125,
                            Nombre = "Graneros",
                            RegionId = 8
                        },
                        new
                        {
                            ComunaId = 126,
                            Nombre = "Mostazal",
                            RegionId = 8
                        },
                        new
                        {
                            ComunaId = 127,
                            Nombre = "San Francisco de Mostazal",
                            RegionId = 8
                        },
                        new
                        {
                            ComunaId = 128,
                            Nombre = "Codegua",
                            RegionId = 8
                        },
                        new
                        {
                            ComunaId = 129,
                            Nombre = "Doñihue",
                            RegionId = 8
                        },
                        new
                        {
                            ComunaId = 130,
                            Nombre = "Coltauco",
                            RegionId = 8
                        },
                        new
                        {
                            ComunaId = 131,
                            Nombre = "Peumo",
                            RegionId = 8
                        },
                        new
                        {
                            ComunaId = 132,
                            Nombre = "Las Cabras",
                            RegionId = 8
                        },
                        new
                        {
                            ComunaId = 133,
                            Nombre = "San Vicente",
                            RegionId = 8
                        },
                        new
                        {
                            ComunaId = 134,
                            Nombre = "Pichidegua",
                            RegionId = 8
                        },
                        new
                        {
                            ComunaId = 135,
                            Nombre = "Rengo",
                            RegionId = 8
                        },
                        new
                        {
                            ComunaId = 136,
                            Nombre = "Requínoa",
                            RegionId = 8
                        },
                        new
                        {
                            ComunaId = 137,
                            Nombre = "Malloa",
                            RegionId = 8
                        },
                        new
                        {
                            ComunaId = 138,
                            Nombre = "San Fernando",
                            RegionId = 8
                        },
                        new
                        {
                            ComunaId = 139,
                            Nombre = "Santa Cruz",
                            RegionId = 8
                        },
                        new
                        {
                            ComunaId = 140,
                            Nombre = "Palmilla",
                            RegionId = 8
                        },
                        new
                        {
                            ComunaId = 141,
                            Nombre = "Peralillo",
                            RegionId = 8
                        },
                        new
                        {
                            ComunaId = 142,
                            Nombre = "Placilla",
                            RegionId = 8
                        },
                        new
                        {
                            ComunaId = 143,
                            Nombre = "Pumanque",
                            RegionId = 8
                        },
                        new
                        {
                            ComunaId = 144,
                            Nombre = "Chimbarongo",
                            RegionId = 8
                        },
                        new
                        {
                            ComunaId = 145,
                            Nombre = "Lolol",
                            RegionId = 8
                        },
                        new
                        {
                            ComunaId = 146,
                            Nombre = "Nancagua",
                            RegionId = 8
                        },
                        new
                        {
                            ComunaId = 147,
                            Nombre = "Paredones",
                            RegionId = 8
                        },
                        new
                        {
                            ComunaId = 148,
                            Nombre = "Pichilemu",
                            RegionId = 8
                        },
                        new
                        {
                            ComunaId = 149,
                            Nombre = "Talca",
                            RegionId = 9
                        },
                        new
                        {
                            ComunaId = 150,
                            Nombre = "Pencahue",
                            RegionId = 9
                        },
                        new
                        {
                            ComunaId = 151,
                            Nombre = "Maule",
                            RegionId = 9
                        },
                        new
                        {
                            ComunaId = 152,
                            Nombre = "San Clemente",
                            RegionId = 9
                        },
                        new
                        {
                            ComunaId = 153,
                            Nombre = "San Rafael",
                            RegionId = 9
                        },
                        new
                        {
                            ComunaId = 154,
                            Nombre = "Curepto",
                            RegionId = 9
                        },
                        new
                        {
                            ComunaId = 155,
                            Nombre = "Constitución",
                            RegionId = 9
                        },
                        new
                        {
                            ComunaId = 156,
                            Nombre = "Empedrado",
                            RegionId = 9
                        },
                        new
                        {
                            ComunaId = 157,
                            Nombre = "Linares",
                            RegionId = 9
                        },
                        new
                        {
                            ComunaId = 158,
                            Nombre = "Longaví",
                            RegionId = 9
                        },
                        new
                        {
                            ComunaId = 159,
                            Nombre = "Colbún",
                            RegionId = 9
                        },
                        new
                        {
                            ComunaId = 160,
                            Nombre = "Retiro",
                            RegionId = 9
                        },
                        new
                        {
                            ComunaId = 161,
                            Nombre = "Villa Alegre",
                            RegionId = 9
                        },
                        new
                        {
                            ComunaId = 162,
                            Nombre = "Yerbas Buenas",
                            RegionId = 9
                        },
                        new
                        {
                            ComunaId = 163,
                            Nombre = "Cauquenes",
                            RegionId = 9
                        },
                        new
                        {
                            ComunaId = 164,
                            Nombre = "Chanco",
                            RegionId = 9
                        },
                        new
                        {
                            ComunaId = 165,
                            Nombre = "Pelluhue",
                            RegionId = 9
                        },
                        new
                        {
                            ComunaId = 166,
                            Nombre = "Curicó",
                            RegionId = 9
                        },
                        new
                        {
                            ComunaId = 167,
                            Nombre = "Hualañé",
                            RegionId = 9
                        },
                        new
                        {
                            ComunaId = 168,
                            Nombre = "Licantén",
                            RegionId = 9
                        },
                        new
                        {
                            ComunaId = 169,
                            Nombre = "Molina",
                            RegionId = 9
                        },
                        new
                        {
                            ComunaId = 170,
                            Nombre = "Rauco",
                            RegionId = 9
                        },
                        new
                        {
                            ComunaId = 171,
                            Nombre = "Romeral",
                            RegionId = 9
                        },
                        new
                        {
                            ComunaId = 172,
                            Nombre = "Sagrada Familia",
                            RegionId = 9
                        },
                        new
                        {
                            ComunaId = 173,
                            Nombre = "Teno",
                            RegionId = 9
                        },
                        new
                        {
                            ComunaId = 174,
                            Nombre = "Vichuquén",
                            RegionId = 9
                        },
                        new
                        {
                            ComunaId = 175,
                            Nombre = "Chillán",
                            RegionId = 10
                        },
                        new
                        {
                            ComunaId = 176,
                            Nombre = "Chillán Viejo",
                            RegionId = 10
                        },
                        new
                        {
                            ComunaId = 177,
                            Nombre = "Quillón",
                            RegionId = 10
                        },
                        new
                        {
                            ComunaId = 178,
                            Nombre = "Bulnes",
                            RegionId = 10
                        },
                        new
                        {
                            ComunaId = 179,
                            Nombre = "San Ignacio",
                            RegionId = 10
                        },
                        new
                        {
                            ComunaId = 180,
                            Nombre = "Pemuco",
                            RegionId = 10
                        },
                        new
                        {
                            ComunaId = 181,
                            Nombre = "El Carmen",
                            RegionId = 10
                        },
                        new
                        {
                            ComunaId = 182,
                            Nombre = "Yungay",
                            RegionId = 10
                        },
                        new
                        {
                            ComunaId = 183,
                            Nombre = "Pinto",
                            RegionId = 10
                        },
                        new
                        {
                            ComunaId = 184,
                            Nombre = "Coihueco",
                            RegionId = 10
                        },
                        new
                        {
                            ComunaId = 185,
                            Nombre = "San Carlos",
                            RegionId = 10
                        },
                        new
                        {
                            ComunaId = 186,
                            Nombre = "Ninhue",
                            RegionId = 10
                        },
                        new
                        {
                            ComunaId = 187,
                            Nombre = "San Nicolás",
                            RegionId = 10
                        },
                        new
                        {
                            ComunaId = 188,
                            Nombre = "Ñiquén",
                            RegionId = 10
                        },
                        new
                        {
                            ComunaId = 189,
                            Nombre = "San Fabián",
                            RegionId = 10
                        },
                        new
                        {
                            ComunaId = 190,
                            Nombre = "Treguaco",
                            RegionId = 10
                        },
                        new
                        {
                            ComunaId = 191,
                            Nombre = "Cobquecura",
                            RegionId = 10
                        },
                        new
                        {
                            ComunaId = 192,
                            Nombre = "Portezuelo",
                            RegionId = 10
                        },
                        new
                        {
                            ComunaId = 193,
                            Nombre = "Ránquil",
                            RegionId = 10
                        },
                        new
                        {
                            ComunaId = 194,
                            Nombre = "Coelemu",
                            RegionId = 10
                        },
                        new
                        {
                            ComunaId = 195,
                            Nombre = "Quirihue",
                            RegionId = 10
                        },
                        new
                        {
                            ComunaId = 196,
                            Nombre = "Chillán Viejo",
                            RegionId = 10
                        },
                        new
                        {
                            ComunaId = 197,
                            Nombre = "Concepción",
                            RegionId = 11
                        },
                        new
                        {
                            ComunaId = 198,
                            Nombre = "Coronel",
                            RegionId = 11
                        },
                        new
                        {
                            ComunaId = 199,
                            Nombre = "Chiguayante",
                            RegionId = 11
                        },
                        new
                        {
                            ComunaId = 200,
                            Nombre = "Florida",
                            RegionId = 11
                        },
                        new
                        {
                            ComunaId = 201,
                            Nombre = "Hualpén",
                            RegionId = 11
                        },
                        new
                        {
                            ComunaId = 202,
                            Nombre = "Hualqui",
                            RegionId = 11
                        },
                        new
                        {
                            ComunaId = 203,
                            Nombre = "Lota",
                            RegionId = 11
                        },
                        new
                        {
                            ComunaId = 204,
                            Nombre = "Penco",
                            RegionId = 11
                        },
                        new
                        {
                            ComunaId = 205,
                            Nombre = "San Pedro de la Paz",
                            RegionId = 11
                        },
                        new
                        {
                            ComunaId = 206,
                            Nombre = "Santa Juana",
                            RegionId = 11
                        },
                        new
                        {
                            ComunaId = 207,
                            Nombre = "Talcahuano",
                            RegionId = 11
                        },
                        new
                        {
                            ComunaId = 208,
                            Nombre = "Tomé",
                            RegionId = 11
                        },
                        new
                        {
                            ComunaId = 209,
                            Nombre = "Los Ángeles",
                            RegionId = 11
                        },
                        new
                        {
                            ComunaId = 210,
                            Nombre = "Antuco",
                            RegionId = 11
                        },
                        new
                        {
                            ComunaId = 211,
                            Nombre = "Cabrero",
                            RegionId = 11
                        },
                        new
                        {
                            ComunaId = 212,
                            Nombre = "Laja",
                            RegionId = 11
                        },
                        new
                        {
                            ComunaId = 213,
                            Nombre = "Mulchén",
                            RegionId = 11
                        },
                        new
                        {
                            ComunaId = 214,
                            Nombre = "Nacimiento",
                            RegionId = 11
                        },
                        new
                        {
                            ComunaId = 215,
                            Nombre = "Negrete",
                            RegionId = 11
                        },
                        new
                        {
                            ComunaId = 216,
                            Nombre = "Quilaco",
                            RegionId = 11
                        },
                        new
                        {
                            ComunaId = 217,
                            Nombre = "Quilleco",
                            RegionId = 11
                        },
                        new
                        {
                            ComunaId = 218,
                            Nombre = "San Rosendo",
                            RegionId = 11
                        },
                        new
                        {
                            ComunaId = 219,
                            Nombre = "Santa Bárbara",
                            RegionId = 11
                        },
                        new
                        {
                            ComunaId = 220,
                            Nombre = "Tucapel",
                            RegionId = 11
                        },
                        new
                        {
                            ComunaId = 221,
                            Nombre = "Yumbel",
                            RegionId = 11
                        },
                        new
                        {
                            ComunaId = 222,
                            Nombre = "Alto Biobío",
                            RegionId = 11
                        },
                        new
                        {
                            ComunaId = 223,
                            Nombre = "Temuco",
                            RegionId = 12
                        },
                        new
                        {
                            ComunaId = 224,
                            Nombre = "Padre Las Casas",
                            RegionId = 12
                        },
                        new
                        {
                            ComunaId = 225,
                            Nombre = "Cunco",
                            RegionId = 12
                        },
                        new
                        {
                            ComunaId = 226,
                            Nombre = "Melipeuco",
                            RegionId = 12
                        },
                        new
                        {
                            ComunaId = 227,
                            Nombre = "Vilcún",
                            RegionId = 12
                        },
                        new
                        {
                            ComunaId = 228,
                            Nombre = "Curarrehue",
                            RegionId = 12
                        },
                        new
                        {
                            ComunaId = 229,
                            Nombre = "Pucón",
                            RegionId = 12
                        },
                        new
                        {
                            ComunaId = 230,
                            Nombre = "Villarrica",
                            RegionId = 12
                        },
                        new
                        {
                            ComunaId = 231,
                            Nombre = "Lautaro",
                            RegionId = 12
                        },
                        new
                        {
                            ComunaId = 232,
                            Nombre = "Perquenco",
                            RegionId = 12
                        },
                        new
                        {
                            ComunaId = 233,
                            Nombre = "Galvarino",
                            RegionId = 12
                        },
                        new
                        {
                            ComunaId = 234,
                            Nombre = "Cholchol",
                            RegionId = 12
                        },
                        new
                        {
                            ComunaId = 235,
                            Nombre = "Nueva Imperial",
                            RegionId = 12
                        },
                        new
                        {
                            ComunaId = 236,
                            Nombre = "Carahue",
                            RegionId = 12
                        },
                        new
                        {
                            ComunaId = 237,
                            Nombre = "Saavedra",
                            RegionId = 12
                        },
                        new
                        {
                            ComunaId = 238,
                            Nombre = "Teodoro Schmidt",
                            RegionId = 12
                        },
                        new
                        {
                            ComunaId = 239,
                            Nombre = "Toltén",
                            RegionId = 12
                        },
                        new
                        {
                            ComunaId = 240,
                            Nombre = "Gorbea",
                            RegionId = 12
                        },
                        new
                        {
                            ComunaId = 241,
                            Nombre = "Loncoche",
                            RegionId = 12
                        },
                        new
                        {
                            ComunaId = 242,
                            Nombre = "Pitrufquén",
                            RegionId = 12
                        },
                        new
                        {
                            ComunaId = 243,
                            Nombre = "Freire",
                            RegionId = 12
                        },
                        new
                        {
                            ComunaId = 244,
                            Nombre = "Renaico",
                            RegionId = 12
                        },
                        new
                        {
                            ComunaId = 245,
                            Nombre = "Angol",
                            RegionId = 12
                        },
                        new
                        {
                            ComunaId = 246,
                            Nombre = "Collipulli",
                            RegionId = 12
                        },
                        new
                        {
                            ComunaId = 247,
                            Nombre = "Curacautín",
                            RegionId = 12
                        },
                        new
                        {
                            ComunaId = 248,
                            Nombre = "Lonquimay",
                            RegionId = 12
                        },
                        new
                        {
                            ComunaId = 249,
                            Nombre = "Ercilla",
                            RegionId = 12
                        },
                        new
                        {
                            ComunaId = 250,
                            Nombre = "Purén",
                            RegionId = 12
                        },
                        new
                        {
                            ComunaId = 251,
                            Nombre = "Los Sauces",
                            RegionId = 12
                        },
                        new
                        {
                            ComunaId = 252,
                            Nombre = "Lumaco",
                            RegionId = 12
                        },
                        new
                        {
                            ComunaId = 253,
                            Nombre = "Traiguén",
                            RegionId = 12
                        },
                        new
                        {
                            ComunaId = 254,
                            Nombre = "Victoria",
                            RegionId = 12
                        },
                        new
                        {
                            ComunaId = 255,
                            Nombre = "Valdivia",
                            RegionId = 13
                        },
                        new
                        {
                            ComunaId = 256,
                            Nombre = "Corral",
                            RegionId = 13
                        },
                        new
                        {
                            ComunaId = 257,
                            Nombre = "Lanco",
                            RegionId = 13
                        },
                        new
                        {
                            ComunaId = 258,
                            Nombre = "Los Lagos",
                            RegionId = 13
                        },
                        new
                        {
                            ComunaId = 259,
                            Nombre = "Máfil",
                            RegionId = 13
                        },
                        new
                        {
                            ComunaId = 260,
                            Nombre = "Mariquina",
                            RegionId = 13
                        },
                        new
                        {
                            ComunaId = 261,
                            Nombre = "Paillaco",
                            RegionId = 13
                        },
                        new
                        {
                            ComunaId = 262,
                            Nombre = "Panguipulli",
                            RegionId = 13
                        },
                        new
                        {
                            ComunaId = 263,
                            Nombre = "La Unión",
                            RegionId = 13
                        },
                        new
                        {
                            ComunaId = 264,
                            Nombre = "Río Bueno",
                            RegionId = 13
                        },
                        new
                        {
                            ComunaId = 265,
                            Nombre = "Futrono",
                            RegionId = 13
                        },
                        new
                        {
                            ComunaId = 266,
                            Nombre = "Lago Ranco",
                            RegionId = 13
                        },
                        new
                        {
                            ComunaId = 269,
                            Nombre = "Puerto Montt",
                            RegionId = 14
                        },
                        new
                        {
                            ComunaId = 270,
                            Nombre = "Puerto Varas",
                            RegionId = 14
                        },
                        new
                        {
                            ComunaId = 271,
                            Nombre = "Llanquihue",
                            RegionId = 14
                        },
                        new
                        {
                            ComunaId = 272,
                            Nombre = "Frutillar",
                            RegionId = 14
                        },
                        new
                        {
                            ComunaId = 273,
                            Nombre = "Los Muermos",
                            RegionId = 14
                        },
                        new
                        {
                            ComunaId = 274,
                            Nombre = "Maullín",
                            RegionId = 14
                        },
                        new
                        {
                            ComunaId = 275,
                            Nombre = "Calbuco",
                            RegionId = 14
                        },
                        new
                        {
                            ComunaId = 276,
                            Nombre = "Cochamó",
                            RegionId = 14
                        },
                        new
                        {
                            ComunaId = 277,
                            Nombre = "Osorno",
                            RegionId = 14
                        },
                        new
                        {
                            ComunaId = 278,
                            Nombre = "Río Negro",
                            RegionId = 14
                        },
                        new
                        {
                            ComunaId = 279,
                            Nombre = "Purranque",
                            RegionId = 14
                        },
                        new
                        {
                            ComunaId = 280,
                            Nombre = "San Pablo",
                            RegionId = 14
                        },
                        new
                        {
                            ComunaId = 281,
                            Nombre = "Puqueldón",
                            RegionId = 14
                        },
                        new
                        {
                            ComunaId = 282,
                            Nombre = "Castro",
                            RegionId = 14
                        },
                        new
                        {
                            ComunaId = 283,
                            Nombre = "Chonchi",
                            RegionId = 14
                        },
                        new
                        {
                            ComunaId = 284,
                            Nombre = "Curaco de Vélez",
                            RegionId = 14
                        },
                        new
                        {
                            ComunaId = 285,
                            Nombre = "Dalcahue",
                            RegionId = 14
                        },
                        new
                        {
                            ComunaId = 286,
                            Nombre = "Puqueldón",
                            RegionId = 14
                        },
                        new
                        {
                            ComunaId = 287,
                            Nombre = "Queilén",
                            RegionId = 14
                        },
                        new
                        {
                            ComunaId = 288,
                            Nombre = "Quellón",
                            RegionId = 14
                        },
                        new
                        {
                            ComunaId = 289,
                            Nombre = "Quemchi",
                            RegionId = 14
                        },
                        new
                        {
                            ComunaId = 290,
                            Nombre = "Quinchao",
                            RegionId = 14
                        },
                        new
                        {
                            ComunaId = 299,
                            Nombre = "Coyhaique",
                            RegionId = 15
                        },
                        new
                        {
                            ComunaId = 300,
                            Nombre = "Lago Verde",
                            RegionId = 15
                        },
                        new
                        {
                            ComunaId = 301,
                            Nombre = "Aysén",
                            RegionId = 15
                        },
                        new
                        {
                            ComunaId = 302,
                            Nombre = "Cisnes",
                            RegionId = 15
                        },
                        new
                        {
                            ComunaId = 303,
                            Nombre = "Guaitecas",
                            RegionId = 15
                        },
                        new
                        {
                            ComunaId = 304,
                            Nombre = "Cochrane",
                            RegionId = 15
                        },
                        new
                        {
                            ComunaId = 305,
                            Nombre = "O’Higgins",
                            RegionId = 15
                        },
                        new
                        {
                            ComunaId = 306,
                            Nombre = "Tortel",
                            RegionId = 15
                        },
                        new
                        {
                            ComunaId = 307,
                            Nombre = "Chile Chico",
                            RegionId = 15
                        },
                        new
                        {
                            ComunaId = 308,
                            Nombre = "Río Ibáñez",
                            RegionId = 15
                        },
                        new
                        {
                            ComunaId = 313,
                            Nombre = "Punta Arenas",
                            RegionId = 16
                        },
                        new
                        {
                            ComunaId = 314,
                            Nombre = "Río Verde",
                            RegionId = 16
                        },
                        new
                        {
                            ComunaId = 315,
                            Nombre = "Laguna Blanca",
                            RegionId = 16
                        },
                        new
                        {
                            ComunaId = 316,
                            Nombre = "San Gregorio",
                            RegionId = 16
                        },
                        new
                        {
                            ComunaId = 317,
                            Nombre = "Puerto Natales",
                            RegionId = 16
                        },
                        new
                        {
                            ComunaId = 318,
                            Nombre = "Torres del Paine",
                            RegionId = 16
                        },
                        new
                        {
                            ComunaId = 319,
                            Nombre = "Porvenir",
                            RegionId = 16
                        },
                        new
                        {
                            ComunaId = 320,
                            Nombre = "Primavera",
                            RegionId = 16
                        },
                        new
                        {
                            ComunaId = 321,
                            Nombre = "Timaukel",
                            RegionId = 16
                        },
                        new
                        {
                            ComunaId = 322,
                            Nombre = "Cabo de Hornos",
                            RegionId = 16
                        },
                        new
                        {
                            ComunaId = 323,
                            Nombre = "Antártica",
                            RegionId = 16
                        });
                });

            modelBuilder.Entity("GestionClientesEcoMercadoAustral.Models.Region", b =>
                {
                    b.Property<int>("RegionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RegionId"));

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("RegionId");

                    b.ToTable("Regiones");

                    b.HasData(
                        new
                        {
                            RegionId = 1,
                            Codigo = "15",
                            Nombre = "Región de Arica y Parinacota"
                        },
                        new
                        {
                            RegionId = 2,
                            Codigo = "01",
                            Nombre = "Región de Tarapacá"
                        },
                        new
                        {
                            RegionId = 3,
                            Codigo = "02",
                            Nombre = "Región de Antofagasta"
                        },
                        new
                        {
                            RegionId = 4,
                            Codigo = "03",
                            Nombre = "Región de Atacama"
                        },
                        new
                        {
                            RegionId = 5,
                            Codigo = "04",
                            Nombre = "Región de Coquimbo"
                        },
                        new
                        {
                            RegionId = 6,
                            Codigo = "05",
                            Nombre = "Región de Valparaíso"
                        },
                        new
                        {
                            RegionId = 7,
                            Codigo = "13",
                            Nombre = "Región Metropolitana de Santiago"
                        },
                        new
                        {
                            RegionId = 8,
                            Codigo = "06",
                            Nombre = "Región del Libertador General Bernardo O’Higgins"
                        },
                        new
                        {
                            RegionId = 9,
                            Codigo = "07",
                            Nombre = "Región del Maule"
                        },
                        new
                        {
                            RegionId = 10,
                            Codigo = "16",
                            Nombre = "Región de Ñuble"
                        },
                        new
                        {
                            RegionId = 11,
                            Codigo = "08",
                            Nombre = "Región del Biobío"
                        },
                        new
                        {
                            RegionId = 12,
                            Codigo = "09",
                            Nombre = "Región de La Araucanía"
                        },
                        new
                        {
                            RegionId = 13,
                            Codigo = "14",
                            Nombre = "Región de Los Ríos"
                        },
                        new
                        {
                            RegionId = 14,
                            Codigo = "10",
                            Nombre = "Región de Los Lagos"
                        },
                        new
                        {
                            RegionId = 15,
                            Codigo = "11",
                            Nombre = "Región de Aysén del General Carlos Ibáñez del Campo"
                        },
                        new
                        {
                            RegionId = 16,
                            Codigo = "12",
                            Nombre = "Región de Magallanes y de la Antártica Chilena"
                        });
                });

            modelBuilder.Entity("GestionClientesEcoMercadoAustral.Models.SegmentoCliente", b =>
                {
                    b.Property<int>("SegmentoClienteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SegmentoClienteId"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NombreSegmento")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SegmentoClienteId");

                    b.ToTable("SegmentosCliente");

                    b.HasData(
                        new
                        {
                            SegmentoClienteId = 1,
                            Descripcion = "Clientes mayoristas",
                            Estado = "Vigente",
                            NombreSegmento = "Mayorista"
                        },
                        new
                        {
                            SegmentoClienteId = 2,
                            Descripcion = "Clientes minoristas",
                            Estado = "Vigente",
                            NombreSegmento = "Minorista"
                        },
                        new
                        {
                            SegmentoClienteId = 3,
                            Descripcion = "Clientes restaurantes",
                            Estado = "Vigente",
                            NombreSegmento = "Restaurante"
                        },
                        new
                        {
                            SegmentoClienteId = 4,
                            Descripcion = "Clientes institucionales",
                            Estado = "Vigente",
                            NombreSegmento = "Instituciones"
                        },
                        new
                        {
                            SegmentoClienteId = 5,
                            Descripcion = "Otros tipos de clientes",
                            Estado = "Vigente",
                            NombreSegmento = "Otro"
                        });
                });

            modelBuilder.Entity("GestionClientesEcoMercadoAustral.Models.Usuario", b =>
                {
                    b.Property<int>("UsuarioId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UsuarioId"));

                    b.Property<string>("Apellido1")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Apellido2")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Rol")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Rut")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UsuarioId");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Usuarios");

                    b.HasData(
                        new
                        {
                            UsuarioId = 1,
                            Apellido1 = "Basoalto",
                            Apellido2 = "Gallegos",
                            Nombre = "Gonzalo",
                            Password = "admin123",
                            Rol = "Administrador",
                            Rut = "15.907.638-5",
                            Username = "admin"
                        },
                        new
                        {
                            UsuarioId = 2,
                            Apellido1 = "Perez",
                            Apellido2 = "Lopez",
                            Nombre = "Juan",
                            Password = "user123",
                            Rol = "Vendedor",
                            Rut = "12.345.678-9",
                            Username = "user"
                        });
                });

            modelBuilder.Entity("GestionClientesEcoMercadoAustral.Models.Cliente", b =>
                {
                    b.HasOne("GestionClientesEcoMercadoAustral.Models.Comuna", "Comuna")
                        .WithMany()
                        .HasForeignKey("ComunaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GestionClientesEcoMercadoAustral.Models.SegmentoCliente", "SegmentoCliente")
                        .WithMany("Clientes")
                        .HasForeignKey("SegmentoClienteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GestionClientesEcoMercadoAustral.Models.Usuario", "Usuario")
                        .WithMany("Clientes")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Comuna");

                    b.Navigation("SegmentoCliente");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("GestionClientesEcoMercadoAustral.Models.Comuna", b =>
                {
                    b.HasOne("GestionClientesEcoMercadoAustral.Models.Region", "Region")
                        .WithMany("Comunas")
                        .HasForeignKey("RegionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Region");
                });

            modelBuilder.Entity("GestionClientesEcoMercadoAustral.Models.Region", b =>
                {
                    b.Navigation("Comunas");
                });

            modelBuilder.Entity("GestionClientesEcoMercadoAustral.Models.SegmentoCliente", b =>
                {
                    b.Navigation("Clientes");
                });

            modelBuilder.Entity("GestionClientesEcoMercadoAustral.Models.Usuario", b =>
                {
                    b.Navigation("Clientes");
                });
#pragma warning restore 612, 618
        }
    }
}
